name: Java CI

on:
  push:
    branches:
      - 'main'
      - 'feature/av004'

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_DB: ${{ secrets.DB_TEST }}
          POSTGRES_USER: ${{ secrets.USER_TEST }}
          POSTGRES_PASSWORD: ${{ secrets.PASSWORD_TEST }}
#          POSTGRES_HOST_AUTH_METHOD: trust
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Flyway Migration
        uses: joshuaavalon/flyway-action@v3.0.0
        with:
          url: ${{ secrets.URL_TEST }}
          user: ${{ secrets.USER_TEST }}
          password: ${{ secrets.PASSWORD_TEST }}
          locations: filesystem:./migration
      - run: echo 'testing'

      #      - name: start mysql
      #        run: sudo /etc/init.d/mysql start
#      - name: start postgresql
#        run: sudo service postgresql start

      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots package
