name: Java CI

on:
  push:
    branches:
      - 'main'
      - 'feature/av004'

jobs:
  build:
    runs-on: ubuntu-latest
    

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'          
#      - name: Flyway-migration-action
#        uses: rahulmalewadi/flyway-custom-action@v1.0.0
#        with:
#          url: DB_BUILD_URL
#          user: DB_BUILD_USERNAME
#          password: DB_BUILD_PASSWORD
#          locations: filesystem:./sql

      - name: start mysql
        run: sudo /etc/init.d/mysql start
      #- name: start postgresql
      #  run: sudo service postgresql start

      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots package
