name: Java CI

on:
  push:
    branches:
      - 'main'
      - 'feature/av004'

jobs:
  build:
    runs-on: ubuntu-latest
    # Service containers to run with `container-job`
    services:
      # Label used to access the service container
      postgres:
        # Docker Hub image
        image: postgres:11.6-alpine
        # Provide the password for postgres
        env:
#          PGUSER: postgres
#          PGPASSWORD: postgres
#          PGDATABASE: postgres
#          POSTGRES_USER: postgres
#          POSTGRES_PASSWORD: postgres
          POSTGRES_PASSWORD: password
#          POSTGRES_DB: postgres
          ports: 5432:5432

        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      #      - name: start mysql
      #        run: sudo /etc/init.d/mysql start
      #      - name: start postgresql
      #        run: sudo service postgresql start
      #        env:
      #            POSTGRES_HOST: postgres
      #            POSTGRES_PASSWORD: postgres
      #            POSTGRES_PORT: 5432

#      - name: Build with Maven
#        run: mvn --batch-mode --update-snapshots package
