name: Java CI

on:
  push:
    branches:
      - 'main'
      - 'feature/av004'

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Setup Postgres database
        uses: Daniel-Marynicz/postgresql-action@master
        with:
          postgres_image_tag: 12-alpine
          app_user: app
          app_user_password: develop
          app_db: app app2 app3 app4
          postgres_extensions: uuid-ossp ltree 
                      
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots package
